name: game_dicovery_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- CORE UTILITIES ---
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2 
  cupertino_icons: ^1.0.8

  # --- FIREBASE & AUTHENTICATION ---
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1 
  
  # --- FIREBASE TESTING INTERFACES ---
  # Required for setting up mocks in the test files (replaces the incorrect firebase_core_testing)
  firebase_core_platform_interface: ^5.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # --- DEVELOPMENT & MOCKING TOOLS ---
  # Moved from dependencies to dev_dependencies
  build_runner: ^2.4.6 
  mockito: ^5.4.0 
  flutter_launcher_icons: ^0.13.1 # Tool for creating launcher icons
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/my_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/my_icon.png
    - assets/google_logo.png